config/routes.rb
Listitems::Application.routes.draw do
 
  devise_for :users
  
  root 'home#index'

  resources :classifieds 

  

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/classified.rb
class Classified < ActiveRecord::Base
  belongs_to :cateory
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :classifieds
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController

  def list
  end  
  
  def new
    @classified = Classified.new
  end
  
  def save
  end   

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/classifieds/_form.html.erb
<%= form_for(@classified) do |f| %>
  <% if @classified.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classified.errors.count, "error") %> prohibited this lassified from being saved:</h2>

      <ul>
      <% @classified.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select(:category_id, Category.all.collect {|cat| [cat.name, cat.id]}, :prompt => 'Select') %>
  </div>
    <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area(:description, :cols => "70", :rows => "10") %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-medium btn-primary"%>
  </div>
<% end %>

app/views/classifieds/list.html.erb
<h1>List item</h1>

app/views/classifieds/new.html.erb
<div class="form">

  <h1>+list an item</h1>

  <%= render 'form' %>

  <%= link_to 'Back', classifieds_path %>
</div>

app/views/home/index.html.erb
<h1>Welcome to listitems</h1>

    <%=link_to '+ List an item', new_classified_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Listitems</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "bootstrap", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container'>
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Home</a>
  </div>

<ul class="nav navbar-nav navbar-right">
      <li><a href="#">Link</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->

  <%= yield %>
</div>

</body>
</html>